routes:
  _controller_action:
    pattern: "{controller}/{action}"
    method: console

  _controller_index:
    pattern: "{controller}/?"
    method: console

  _default:
    pattern: ".*"
    controller: Index
    method: console